/* ============================================================
   Hindi Speak — the study booklet, in the app, with the machine
   listening. Crispin does not speak Hindi, so "I read it correctly"
   self-marking is exactly how a wrong pronunciation sticks. Here the
   browser listens (hi-IN speech recognition), compares what it heard
   with the target, and says WHICH word was wrong.

   Content comes from data/hy-hindi-study.js, which is generated by
   tools/build_hindi_booklet.py — the same source as the printed
   booklet, so the two cannot drift.

   Self-contained: own namespace (.hs-*), own localStorage key.
   ============================================================ */
(function () {
  'use strict';

  const KEY = 'crispin_hindi_speak_v1';
  const OK = 0.85;          // word-level similarity that counts as correct
  const SENT_OK = 0.8;      // share of words that must match in a sentence
  const LISTEN_MS = 7000;

  /* ---------------- progress ---------------- */
  function load() {
    try { return JSON.parse(localStorage.getItem(KEY)) || {}; } catch (_) { return {}; }
  }
  function save(s) { try { localStorage.setItem(KEY, JSON.stringify(s)); } catch (_) {} }
  let stats = load();

  function record(id, score) {
    const r = stats[id] || { n: 0, best: 0 };
    r.n += 1;
    const wasMastered = r.best >= OK;
    r.best = Math.max(r.best, score);
    stats[id] = r;
    save(stats);
    if (!wasMastered && r.best >= OK && window.Progress && Progress.addXP) {
      try { Progress.addXP(2, 'Hindi pronunciation'); } catch (_) {}
    }
    return r;
  }

  /* ---------------- Devanagari helpers ---------------- */
  // Fold nukta and punctuation so "आवाज़" and "आवाज" compare equal.
  function norm(s) {
    return String(s || '')
      .normalize('NFD').replace(/़/g, '').normalize('NFC')
      .replace(/[।॥.,!?"'“”‘’:;()\-–—]/g, ' ')
      .replace(/\s+/g, ' ')
      .trim();
  }
  const AKSHARA = /[ऀ-ॿ][़ऀ-ःऺ-ौॎ-ॗॢॣ]*(?:्[ऀ-ॿ][़ऀ-ःऺ-ौ]*)*/g;
  function syllables(word) {
    const m = String(word || '').match(AKSHARA);
    return m ? m.join(' · ') : word;
  }
  function lev(a, b) {
    const m = a.length, n = b.length;
    if (!m) return n;
    if (!n) return m;
    let prev = new Array(n + 1), cur = new Array(n + 1);
    for (let j = 0; j <= n; j++) prev[j] = j;
    for (let i = 1; i <= m; i++) {
      cur[0] = i;
      for (let j = 1; j <= n; j++) {
        cur[j] = Math.min(prev[j] + 1, cur[j - 1] + 1, prev[j - 1] + (a[i - 1] === b[j - 1] ? 0 : 1));
      }
      const t = prev; prev = cur; cur = t;
    }
    return prev[n];
  }
  function sim(a, b) {
    a = norm(a); b = norm(b);
    if (!a || !b) return 0;
    if (a === b) return 1;
    return Math.max(0, 1 - lev(a, b) / Math.max(a.length, b.length));
  }
  // For a sentence: which target words did the machine hear?
  // Compare on the normalised form, but report the word as HE sees it on the card —
  // showing him "पेड" when the card says "पेड़" would teach the wrong spelling.
  function wordCheck(target, heard) {
    const raw = String(target || '').split(/\s+/).filter(Boolean);
    const hw = norm(heard).split(' ').filter(Boolean);
    const marks = [];
    raw.forEach(function (original) {
      const w = norm(original);
      if (!w) return;
      let best = 0;
      hw.forEach(function (h) { best = Math.max(best, sim(w, h)); });
      marks.push({ word: original, ok: best >= 0.8, score: best });
    });
    const good = marks.filter(function (m) { return m.ok; }).length;
    return { marks: marks, score: marks.length ? good / marks.length : 0 };
  }

  /* ---------------- speech out ---------------- */
  let hiVoice = null;
  function pickHi() {
    if (hiVoice) return hiVoice;
    const v = (window.speechSynthesis && speechSynthesis.getVoices()) || [];
    hiVoice = v.filter(function (x) { return /^hi/i.test(x.lang || ''); })[0] || null;
    return hiVoice;
  }
  function say(text, slow) {
    if (!('speechSynthesis' in window)) return;
    try { speechSynthesis.cancel(); } catch (_) {}
    const fire = function () {
      const u = new SpeechSynthesisUtterance(String(text).replace(/\s+/g, ' ').trim());
      u.lang = 'hi-IN';
      u.rate = slow ? 0.5 : 0.8;
      const v = pickHi(); if (v) u.voice = v;
      try { speechSynthesis.speak(u); } catch (_) {}
    };
    if (!speechSynthesis.getVoices().length) {
      speechSynthesis.addEventListener('voiceschanged', fire, { once: true });
      setTimeout(fire, 300);
    } else fire();
  }
  function hasHindiVoice() { return !!pickHi(); }

  /* ---------------- speech in ---------------- */
  const SR = window.SpeechRecognition || window.webkitSpeechRecognition;
  let active = null;
  function listen(cb) {
    if (!SR) { cb({ error: 'unsupported' }); return null; }
    if (active) { try { active.abort(); } catch (_) {} active = null; }
    let done = false;
    const r = new SR();
    r.lang = 'hi-IN';
    r.interimResults = false;
    r.maxAlternatives = 5;
    r.continuous = false;
    const finish = function (payload) {
      if (done) return; done = true;
      active = null;
      try { r.stop(); } catch (_) {}
      cb(payload);
    };
    r.onresult = function (e) {
      const alts = [];
      for (let i = 0; i < e.results[0].length; i++) alts.push(e.results[0][i].transcript);
      finish({ alts: alts });
    };
    r.onerror = function (e) { finish({ error: e.error || 'error' }); };
    r.onend = function () { if (!done) finish({ error: 'no-speech' }); };
    try { r.start(); } catch (_) { finish({ error: 'error' }); return null; }
    active = r;
    setTimeout(function () { if (!done) { try { r.stop(); } catch (_) {} } }, LISTEN_MS);
    return r;
  }

  /* ---------------- fallback: record and compare ---------------- */
  const canRecord = !!(navigator.mediaDevices && window.MediaRecorder);
  function recordClip(ms, cb) {
    navigator.mediaDevices.getUserMedia({ audio: true }).then(function (stream) {
      const chunks = [];
      const mr = new MediaRecorder(stream);
      mr.ondataavailable = function (e) { if (e.data.size) chunks.push(e.data); };
      mr.onstop = function () {
        stream.getTracks().forEach(function (t) { t.stop(); });
        cb(URL.createObjectURL(new Blob(chunks, { type: chunks[0] ? chunks[0].type : 'audio/webm' })));
      };
      mr.start();
      setTimeout(function () { try { mr.stop(); } catch (_) {} }, ms);
    }).catch(function () { cb(null); });
  }

  /* ---------------- items ---------------- */
  function buildItems(D) {
    const items = { shabd: [], kahani: [], kavita: [], uttar: [], vyakaran: [] };
    const seen = {};
    const pushWord = function (list, hi, roman, en, tag) {
      if (!hi || seen[tag + hi]) return;
      seen[tag + hi] = 1;
      list.push({ id: tag + ':' + hi, hi: hi, roman: roman || '', en: en || '', tag: tag, kind: 'word' });
    };
    D.words.forEach(function (w) {
      pushWord(items.shabd, w.hi, w.roman, w.en, w.kind);
      String(w.answer || '').split(',').forEach(function (part, i) {
        pushWord(items.shabd, part.trim(), i === 0 ? w.answerRoman : '', w.answerEn, w.kind);
      });
    });
    D.story.sentences.forEach(function (s, i) {
      items.kahani.push({ id: 'kahani:' + i, hi: s, en: '', tag: 'कहानी', kind: 'sentence' });
    });
    D.poem.forEach(function (c, i) {
      items.kavita.push({ id: 'kavita:' + i + 'a', hi: c.a, en: c.en, tag: 'कविता', kind: 'sentence' });
      items.kavita.push({ id: 'kavita:' + i + 'b', hi: c.b, en: '', tag: 'कविता', kind: 'sentence' });
    });
    D.qa.forEach(function (q, i) {
      items.uttar.push({ id: 'uttar:' + i, hi: q.a, en: q.aEn, q: q.q, qEn: q.qEn, tag: q.chapter, kind: 'sentence' });
    });
    D.grammar.forEach(function (g) {
      items.vyakaran.push({ id: 'def:' + g.id, hi: g.def, en: g.defEn, tag: g.title + ' · परिभाषा', kind: 'sentence' });
      (g.kinds || []).forEach(function (k) {
        (k.words || []).forEach(function (w) {
          pushWord(items.vyakaran, w.hi, '', w.en, g.title + ' · ' + k.hi);
        });
      });
      (g.pairs || []).forEach(function (pr) {
        pushWord(items.vyakaran, pr.hi, '', pr.en, g.title);
        pushWord(items.vyakaran, pr.answer, '', pr.answerEn, g.title);
      });
      (g.sort || []).forEach(function (w) { pushWord(items.vyakaran, w.hi, '', w.en, g.title); });
      (g.words || []).forEach(function (w) { pushWord(items.vyakaran, w.hi, '', w.en, g.title); });
    });
    return items;
  }

  /* ---------------- UI ---------------- */
  const TABS = [
    { id: 'shabd', label: 'शब्द', en: 'words' },
    { id: 'kahani', label: 'कहानी', en: 'the story' },
    { id: 'kavita', label: 'कविता', en: 'the poem' },
    { id: 'uttar', label: 'प्रश्न-उत्तर', en: 'answers' },
    { id: 'vyakaran', label: 'व्याकरण', en: 'grammar' },
    { id: 'mushkil', label: 'मुश्किल शब्द', en: 'my hard words' }
  ];

  function esc(s) {
    return String(s == null ? '' : s).replace(/[&<>"]/g, function (c) {
      return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c];
    });
  }

  const HS = {};
  HS.mount = function (hostSel, D) {
    const host = document.querySelector(hostSel);
    if (!host || !D) return;
    const items = buildItems(D);
    let tab = 'shabd';

    function allItems() {
      return TABS.slice(0, 5).reduce(function (a, t) { return a.concat(items[t.id]); }, []);
    }
    function hardItems() {
      return allItems().filter(function (it) {
        const r = stats[it.id];
        return r && r.best < OK;
      }).sort(function (a, b) { return (stats[a.id].best || 0) - (stats[b.id].best || 0); });
    }
    function counts() {
      const all = allItems();
      const done = all.filter(function (it) { return stats[it.id] && stats[it.id].best >= OK; }).length;
      return { done: done, total: all.length };
    }

    function head() {
      const c = counts();
      const pct = c.total ? Math.round(c.done / c.total * 100) : 0;
      const support = SR
        ? '<span class="hs-ok">🎤 माइक तैयार है · the app can hear you</span>'
        : (canRecord
          ? '<span class="hs-warn">🎙️ This browser cannot check Hindi speech. You can still record yourself and compare. For checking, open this page in <b>Chrome</b>.</span>'
          : '<span class="hs-warn">🎤 No microphone support in this browser — open in <b>Chrome</b>.</span>');
      const voice = hasHindiVoice() ? '' :
        '<div class="hs-warn hs-warn--row">🔊 No Hindi voice is installed on this device yet, so “सुनो” may sound wrong. On Windows: Settings → Time &amp; language → Language → add <b>हिन्दी</b> speech.</div>';
      return '<div class="hs-head">' +
        '<div class="hs-bar"><div class="hs-bar__fill" style="width:' + pct + '%"></div></div>' +
        '<div class="hs-head__row"><b>' + c.done + ' / ' + c.total + '</b> सही बोले गए · spoken correctly' +
        '<span class="hs-support">' + support + '</span></div>' + voice + '</div>';
    }

    function tabsHtml() {
      return '<div class="hs-tabs">' + TABS.map(function (t) {
        const n = t.id === 'mushkil' ? hardItems().length : items[t.id].length;
        return '<button class="hs-tab' + (t.id === tab ? ' is-on' : '') + '" data-tab="' + t.id + '">' +
          '<span class="hs-tab__hi">' + t.label + '</span><span class="hs-tab__en">' + t.en + ' · ' + n + '</span></button>';
      }).join('') + '</div>';
    }

    function cardHtml(it) {
      const r = stats[it.id];
      const state = r ? (r.best >= OK ? 'ok' : 'try') : '';
      const big = it.kind === 'word' ? 'hs-hi--word' : 'hs-hi--sent';
      return '<div class="hs-card' + (state ? ' is-' + state : '') + '" data-id="' + esc(it.id) + '">' +
        '<div class="hs-card__tag">' + esc(it.tag || '') + (r && r.best >= OK ? ' <span class="hs-tick">✓</span>' : '') + '</div>' +
        (it.q ? '<div class="hs-q">' + esc(it.q) + (it.qEn ? '<i> — ' + esc(it.qEn) + '</i>' : '') + '</div>' : '') +
        '<div class="hs-hi ' + big + '">' + esc(it.hi) + '</div>' +
        (it.roman ? '<div class="hs-roman">' + esc(it.roman) + '</div>' : '') +
        (it.en ? '<div class="hs-en">' + esc(it.en) + '</div>' : '') +
        '<div class="hs-btns">' +
        '<button class="hs-btn hs-btn--hear" data-act="hear">🔊 सुनो</button>' +
        '<button class="hs-btn hs-btn--slow" data-act="slow">🐢 धीरे</button>' +
        '<button class="hs-btn hs-btn--mic" data-act="speak">🎤 बोलो</button>' +
        '</div>' +
        '<div class="hs-result" hidden></div>' +
        '</div>';
    }

    function listHtml() {
      const list = tab === 'mushkil' ? hardItems() : items[tab];
      if (!list.length) {
        return '<p class="hs-empty">' + (tab === 'mushkil'
          ? 'अभी कोई मुश्किल शब्द नहीं। 🎉 <i>Nothing to drill — speak some words first, and anything you get wrong lands here.</i>'
          : 'कुछ नहीं मिला।') + '</p>';
      }
      return '<div class="hs-grid">' + list.map(cardHtml).join('') + '</div>';
    }

    function render() {
      host.innerHTML = head() + tabsHtml() + listHtml();
    }

    /* ---- speaking flow ---- */
    function showResult(card, it, heard, score, marks) {
      const box = card.querySelector('.hs-result');
      box.hidden = false;
      let html;
      if (score >= OK) {
        html = '<div class="hs-verdict hs-verdict--ok">✅ बहुत बढ़िया! <i>That sounded right.</i></div>';
      } else {
        const pieces = marks
          ? '<div class="hs-words">' + marks.map(function (m) {
            return '<span class="' + (m.ok ? 'hs-w hs-w--ok' : 'hs-w hs-w--bad') + '">' + esc(m.word) + '</span>';
          }).join(' ') + '</div><p class="hs-tip">लाल शब्द फिर से बोलो। <i>The words in red did not come through — tap 🐢 and copy them slowly.</i></p>'
          : '<p class="hs-tip">इसे धीरे बोलो: <b>' + esc(syllables(it.hi)) + '</b></p>';
        html = '<div class="hs-verdict hs-verdict--try">🤔 मैंने यह सुना: “<b>' + esc(heard || '—') + '</b>”</div>' + pieces;
      }
      html += '<div class="hs-btns hs-btns--after">' +
        '<button class="hs-btn hs-btn--slow" data-act="slow">🐢 फिर सुनो</button>' +
        '<button class="hs-btn hs-btn--mic" data-act="speak">🎤 फिर बोलो</button>' +
        '<button class="hs-btn hs-btn--ghost" data-act="ok">मैंने सही बोला ✓</button></div>';
      box.innerHTML = html;
    }

    function speakFlow(card, it) {
      const box = card.querySelector('.hs-result');
      const mic = card.querySelector('[data-act="speak"]');
      box.hidden = false;
      box.innerHTML = '<div class="hs-listening">🎤 सुन रहा हूँ… <i>say it now</i></div>';
      card.classList.add('is-listening');
      if (mic) mic.disabled = true;

      const finish = function () { card.classList.remove('is-listening'); if (mic) mic.disabled = false; };

      if (!SR) {
        if (!canRecord) {
          // No recognition and no recorder (older iPad Safari). Never leave him stuck:
          // he can still listen, copy, and mark it himself.
          finish();
          box.innerHTML = '<p class="hs-tip">यह ब्राउज़र सुन नहीं सकता। <i>This browser cannot listen. ' +
            'Open this page in <b>Chrome</b> to have your Hindi checked — meanwhile, listen and copy.</i></p>' +
            '<div class="hs-btns hs-btns--after">' +
            '<button class="hs-btn hs-btn--hear" data-act="hear">🔊 सुनो</button>' +
            '<button class="hs-btn hs-btn--slow" data-act="slow">🐢 धीरे</button>' +
            '<button class="hs-btn hs-btn--ghost" data-act="ok">मैंने सही बोला ✓</button></div>';
          return;
        }
        box.innerHTML = '<div class="hs-listening">🎙️ रिकॉर्ड हो रहा है… <i>recording 4 seconds</i></div>';
        recordClip(4000, function (url) {
          finish();
          if (!url) { box.innerHTML = '<p class="hs-tip">Microphone was blocked.</p>'; return; }
          box.innerHTML = '<div class="hs-verdict">🎧 अब मिलाओ · compare the two</div>' +
            '<div class="hs-btns hs-btns--after">' +
            '<button class="hs-btn hs-btn--hear" data-act="hear">🔊 सही उच्चारण</button>' +
            '<button class="hs-btn hs-btn--play" data-act="playme">▶️ मेरी आवाज़</button>' +
            '<button class="hs-btn hs-btn--mic" data-act="speak">🎤 फिर बोलो</button>' +
            '<button class="hs-btn hs-btn--ghost" data-act="ok">मैंने सही बोला ✓</button></div>';
          card.dataset.clip = url;
        });
        return;
      }

      listen(function (res) {
        finish();
        if (res.error) {
          const msg = {
            'not-allowed': 'माइक बंद है। <i>Allow the microphone for this site, then tap 🎤 again.</i>',
            'no-speech': 'कुछ सुनाई नहीं दिया। <i>Nothing came through — tap 🎤 and speak straight after the beep.</i>',
            'audio-capture': 'माइक नहीं मिला। <i>No microphone found.</i>',
            'network': 'इंटरनेट चाहिए। <i>Speech checking needs the internet.</i>',
            'unsupported': 'This browser cannot check Hindi speech — open in <b>Chrome</b>.'
          }[res.error] || 'फिर से कोशिश करो। <i>Something went wrong — try again.</i>';
          box.innerHTML = '<p class="hs-tip">' + msg + '</p>' +
            '<div class="hs-btns hs-btns--after"><button class="hs-btn hs-btn--mic" data-act="speak">🎤 फिर बोलो</button></div>';
          return;
        }
        let best = { score: 0, heard: res.alts[0] || '', marks: null };
        res.alts.forEach(function (alt) {
          if (it.kind === 'sentence') {
            const wc = wordCheck(it.hi, alt);
            if (wc.score > best.score) best = { score: wc.score, heard: alt, marks: wc.marks };
          } else {
            const sc = sim(it.hi, alt);
            if (sc > best.score) best = { score: sc, heard: alt, marks: null };
          }
        });
        const pass = it.kind === 'sentence' ? best.score >= SENT_OK : best.score >= OK;
        record(it.id, pass ? Math.max(best.score, OK) : best.score);
        showResult(card, it, best.heard, pass ? 1 : best.score, best.marks);
        if (pass) {
          card.classList.remove('is-try'); card.classList.add('is-ok');
          const tag = card.querySelector('.hs-card__tag');
          if (tag && tag.indexOf) tag.innerHTML = tag.innerHTML.replace(' <span class="hs-tick">✓</span>', '') + ' <span class="hs-tick">✓</span>';
        } else {
          card.classList.add('is-try');
        }
        refreshHead();
      });
    }

    function refreshHead() {
      const h = host.querySelector('.hs-head');
      if (h) h.outerHTML = head();
      const t = host.querySelector('.hs-tabs');
      if (t) t.outerHTML = tabsHtml();
    }

    /* ---- events ---- */
    host.addEventListener('click', function (e) {
      const tabBtn = e.target.closest('[data-tab]');
      if (tabBtn) { tab = tabBtn.dataset.tab; render(); return; }
      const btn = e.target.closest('[data-act]');
      if (!btn) return;
      const card = btn.closest('.hs-card');
      if (!card) return;
      const id = card.dataset.id;
      const it = allItems().filter(function (x) { return x.id === id; })[0];
      if (!it) return;
      const act = btn.dataset.act;
      if (act === 'hear') say(it.hi, false);
      else if (act === 'slow') say(it.hi, true);
      else if (act === 'speak') speakFlow(card, it);
      else if (act === 'playme') { if (card.dataset.clip) new Audio(card.dataset.clip).play(); }
      else if (act === 'ok') {
        record(it.id, 1);
        card.classList.remove('is-try'); card.classList.add('is-ok');
        const box = card.querySelector('.hs-result');
        box.innerHTML = '<div class="hs-verdict hs-verdict--ok">✅ ठीक है — खुद जाँचा। <i>Marked by you.</i></div>';
        refreshHead();
      }
    });

    render();
  };

  HS.reset = function () { stats = {}; save(stats); };
  // exposed for the smoke test
  HS._sim = sim;
  HS._wordCheck = wordCheck;
  HS._syllables = syllables;
  window.HindiSpeak = HS;
})();
