#!/usr/bin/env python3
"""
Build a curated photo/video manifest for Crispin's birthday slideshow.

Scans `Crispin Photos and Videos/`, picks a balanced sample from each
sub-folder, and writes `data/birthday-memories.js` (a JS file the
slideshow page consumes — no server / directory listing needed).

Output shape:
    window.BIRTHDAY_MEMORIES = {
      sections: [
        { title: "Baby days", emoji: "👶", items: [{ src, type, alt }, ...] },
        ...
      ]
    };

Run:  python tools/build_memories_manifest.py
"""

import json
import os
import random
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PHOTOS_ROOT = ROOT / "Crispin Photos and Videos"
OUT = ROOT / "data" / "birthday-memories.js"

PHOTO_EXTS = {".jpg", ".jpeg", ".png", ".webp"}  # HEIC won't render in browsers
VIDEO_EXTS = {".mp4", ".mov", ".webm", ".m4v"}

# Sub-folder → display config. Order in this list = order in the slideshow.
# `take` is roughly how many items to pull from that folder.
SECTIONS = [
    ("Baptism",                {"title": "Welcome to the world",  "emoji": "👶", "take_photos": 6, "take_videos": 0}),
    ("Crispin",                {"title": "Growing up",            "emoji": "🌱", "take_photos": 8, "take_videos": 1}),
    ("Studio Photographs",     {"title": "Star moments",          "emoji": "⭐", "take_photos": 5, "take_videos": 0}),
    ("With Treesa",            {"title": "With mum",              "emoji": "💕", "take_photos": 2, "take_videos": 0}),
    ("Photos",                 {"title": "Memories",              "emoji": "📸", "take_photos": 14, "take_videos": 1}),
    ("Birthday Celebrations",  {"title": "Birthdays past",        "emoji": "🎂", "take_photos": 8, "take_videos": 2}),
    ("Dance",                  {"title": "Dance moves",           "emoji": "💃", "take_photos": 1, "take_videos": 2}),
    ("Crispin's Friends",      {"title": "With friends",          "emoji": "🤝", "take_photos": 6, "take_videos": 1}),
    ("videos",                 {"title": "Highlights",            "emoji": "🎬", "take_photos": 0, "take_videos": 3}),
]

def collect(folder: Path, exts: set) -> list[Path]:
    """Recursively gather files with matching extensions, sorted by name."""
    if not folder.exists():
        return []
    out = []
    for p in folder.rglob("*"):
        if p.is_file() and p.suffix.lower() in exts:
            out.append(p)
    return sorted(out, key=lambda x: x.name.lower())

def evenly_sample(items: list, n: int) -> list:
    """Pick n items spaced evenly through the list (preserves chronology)."""
    if n <= 0 or not items:
        return []
    if len(items) <= n:
        return list(items)
    step = len(items) / n
    return [items[int(i * step)] for i in range(n)]

def to_url(p: Path) -> str:
    """Convert absolute path to a URL the page can load (relative to project root)."""
    rel = p.relative_to(ROOT)
    # Use forward slashes; spaces and special chars must be percent-encoded
    from urllib.parse import quote
    return quote(str(rel).replace(os.sep, "/"))

def main():
    if not PHOTOS_ROOT.exists():
        print(f"ERROR: {PHOTOS_ROOT} not found", file=sys.stderr)
        sys.exit(1)

    sections_out = []
    total_photos = 0
    total_videos = 0

    for folder_name, cfg in SECTIONS:
        folder = PHOTOS_ROOT / folder_name
        photos = collect(folder, PHOTO_EXTS)
        videos = collect(folder, VIDEO_EXTS)

        chosen_photos = evenly_sample(photos, cfg["take_photos"])
        chosen_videos = evenly_sample(videos, cfg["take_videos"])

        items = []
        for p in chosen_photos:
            items.append({"src": to_url(p), "type": "photo", "alt": p.stem})
        for v in chosen_videos:
            items.append({"src": to_url(v), "type": "video", "alt": v.stem})

        if not items:
            continue

        # Shuffle photos+videos lightly within section so videos don't always trail
        random.Random(folder_name).shuffle(items)

        sections_out.append({
            "title": cfg["title"],
            "emoji": cfg["emoji"],
            "items": items,
        })
        total_photos += len(chosen_photos)
        total_videos += len(chosen_videos)

    payload = {"sections": sections_out}

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w", encoding="utf-8") as f:
        f.write("/* Auto-generated by tools/build_memories_manifest.py — do not edit */\n")
        f.write("window.BIRTHDAY_MEMORIES = ")
        json.dump(payload, f, ensure_ascii=False, indent=2)
        f.write(";\n")

    print(f"OK Wrote {OUT.relative_to(ROOT)}")
    print(f"  Sections: {len(sections_out)}")
    print(f"  Photos:   {total_photos}")
    print(f"  Videos:   {total_videos}")
    for s in sections_out:
        print(f"    - {s['title']}: {len(s['items'])} items")

if __name__ == "__main__":
    main()
