"""Generate large, varied exam banks for chapters 2–10.

Run from the repo root:
    python tools/generate_exam_banks.py

Each chapter produces 70–100 questions of mixed types so that the
exam runner (which picks 25 random items per attempt) gives genuine
variety on retake.
"""
from __future__ import annotations

import io
import json
import random
import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

ROOT = Path(__file__).resolve().parent.parent / "data"


# ---------------- helpers ----------------
def Q(type_, q, options=None, answer=None, explain="", hint=None):
    o = {"type": type_, "q": q}
    if options is not None:
        o["options"] = options
    o["answer"] = answer
    o["explain"] = explain
    if hint:
        o["hint"] = hint
    return o


def write_bank(filename, var_name, qs):
    out = [f"/* Chapter exam bank — {len(qs)} questions, generated by tools/generate_exam_banks.py */"]
    out.append(f"window.{var_name} = [")
    for q in qs:
        parts = [f"type: '{q['type']}'", f"q: {json.dumps(q['q'])}"]
        if "options" in q:
            parts.append(f"options: {json.dumps(q['options'])}")
        parts.append(f"answer: {json.dumps(q['answer'])}")
        parts.append(f"explain: {json.dumps(q['explain'])}")
        if "hint" in q:
            parts.append(f"hint: {json.dumps(q['hint'])}")
        out.append("  { " + ", ".join(parts) + " },")
    out.append("];")
    out.append("")
    path = ROOT / filename
    path.write_text("\n".join(out), encoding="utf-8")
    print(f"  wrote {filename:38s} {len(qs):3d} questions")


def fmt(n):
    """Format integer with comma separators."""
    return f"{n:,}"


# ============================================================
# Ch 2 — The Four Operations
# ============================================================
def gen_ch02():
    random.seed(202)
    qs = []

    # Addition variety
    seen = set()
    while len([q for q in qs if "+" in q["q"]]) < 14:
        a, b = random.randint(100, 9000), random.randint(100, 9000)
        if (a, b) in seen: continue
        seen.add((a, b))
        qs.append(Q("fill", f"{fmt(a)} + {fmt(b)} = ?",
                    answer=[str(a + b), fmt(a + b)],
                    explain=f"{fmt(a)} + {fmt(b)} = {fmt(a + b)}."))

    # Subtraction variety
    while len([q for q in qs if "−" in q["q"]]) < 12:
        a = random.randint(1000, 9999)
        b = random.randint(100, a - 1)
        qs.append(Q("fill", f"{fmt(a)} − {fmt(b)} = ?",
                    answer=[str(a - b), fmt(a - b)],
                    explain=f"{fmt(a)} − {fmt(b)} = {fmt(a - b)}."))

    # Multiplication
    while len([q for q in qs if "×" in q["q"] and "÷" not in q["q"]]) < 12:
        a = random.choice([random.randint(11, 99), random.randint(100, 999)])
        b = random.choice([random.randint(2, 9), random.randint(11, 25)])
        qs.append(Q("fill", f"{a} × {b} = ?",
                    answer=[str(a * b), fmt(a * b)],
                    explain=f"{a} × {b} = {fmt(a * b)}."))

    # Division (clean)
    while len([q for q in qs if "÷" in q["q"]]) < 10:
        b = random.randint(2, 9)
        ans = random.randint(20, 250)
        a = b * ans
        qs.append(Q("fill", f"{fmt(a)} ÷ {b} = ?",
                    answer=[str(ans), fmt(ans)],
                    explain=f"{fmt(a)} ÷ {b} = {ans}."))

    # BODMAS
    bodmas_set = [
        ("(8 + 4) × 3", 36, "Brackets first: 12, then ×3 = 36."),
        ("20 − 6 + 4", 18, "Left to right: 20−6=14, then +4=18."),
        ("6 × 7 + 3", 45, "× before +: 42 + 3 = 45."),
        ("8 ÷ 2 × 3", 12, "÷ and × left-to-right: 4 × 3 = 12."),
        ("15 + 3 × 4", 27, "× first: 12, then +15 = 27."),
        ("(20 − 5) ÷ 3", 5, "Brackets: 15, ÷3 = 5."),
        ("(12 + 8) ÷ 4", 5, "Brackets: 20, ÷4 = 5."),
        ("100 − 10 × 5", 50, "× first: 50, then 100−50 = 50."),
        ("36 ÷ 4 + 6", 15, "÷ first: 9, then +6 = 15."),
    ]
    for expr, ans, ex in bodmas_set:
        qs.append(Q("fill", f"{expr} = ?", answer=[str(ans)], explain=ex))

    # Word problems
    word_problems = [
        ("Crispin has 124 stickers. He gets 87 more. How many now?", 211),
        ("A box has 24 chocolates. How many in 8 boxes?", 192),
        ("5 friends share 85 toffees equally. Each gets?", 17),
        ("Tickets cost ₹50. 17 sold. Total ₹?", 850),
        ("There are 1,250 fans. 875 leave. How many remain?", 375),
        ("A school has 6 classes of 32 children each. Total?", 192),
        ("A book has 240 pages. Crispin read 5/8. How many pages read?", 150),
        ("A baker bakes 144 buns in 6 trays. Buns per tray?", 24),
    ]
    for q, ans in word_problems:
        qs.append(Q("fill", q, answer=[str(ans), fmt(ans)],
                    explain=f"Answer = {fmt(ans)}."))

    # Missing-number
    for _ in range(8):
        a = random.randint(20, 200)
        b = random.randint(20, 200)
        qs.append(Q("fill", f"? + {a} = {a + b}",
                    answer=[str(b), fmt(b)],
                    explain=f"{a + b} − {a} = {b}."))

    # MCQ — vocabulary / order of operations
    qs += [
        Q("mcq", '"Product" means the result of which operation?',
          options=["Addition", "Subtraction", "Multiplication", "Division"],
          answer=2, explain='"Product" = multiplication result.'),
        Q("mcq", '"Quotient" means the result of which operation?',
          options=["Addition", "Subtraction", "Multiplication", "Division"],
          answer=3, explain='"Quotient" = division result.'),
        Q("mcq", '"Sum" means the result of which operation?',
          options=["Addition", "Subtraction", "Multiplication", "Division"],
          answer=0, explain='"Sum" = addition result.'),
        Q("mcq", '"Difference" means the result of which operation?',
          options=["Addition", "Subtraction", "Multiplication", "Division"],
          answer=1, explain='"Difference" = subtraction result.'),
        Q("mcq", "What comes first in BODMAS?",
          options=["Brackets", "Order", "Division", "Add"],
          answer=0, explain="B-O-D-M-A-S: Brackets first."),
        Q("tf", "450 × 1 = 450 is true.", answer=0,
          explain="True — multiplying by 1 keeps the number."),
        Q("tf", "7 + 3 = 3 + 7 (you can swap order in addition).", answer=0,
          explain="True — addition is commutative."),
        Q("tf", "10 − 3 = 3 − 10 (you can swap order in subtraction).", answer=1,
          explain="False — subtraction is NOT commutative."),
        Q("tf", "Anything × 0 = 0.", answer=0, explain="True."),
        Q("tf", "0 ÷ any number = 0 (when the number is not zero).", answer=0,
          explain="True. (But you can't divide by zero!)"),
        Q("fill", "What is the remainder when 47 is divided by 6?",
          answer=["5"], explain="6×7=42, 47−42=5."),
        Q("fill", "What is the remainder when 100 is divided by 7?",
          answer=["2"], explain="7×14=98, 100−98=2."),
    ]
    return qs


# ============================================================
# Ch 3 — Multiples & Factors
# ============================================================
def gen_ch03():
    random.seed(303)
    qs = []

    # Multiples
    multiples_data = [
        (3, 5, "3, 6, 9, 12, 15"),
        (4, 5, "4, 8, 12, 16, 20"),
        (5, 4, "5, 10, 15, 20"),
        (6, 4, "6, 12, 18, 24"),
        (7, 4, "7, 14, 21, 28"),
        (8, 3, "8, 16, 24"),
        (9, 4, "9, 18, 27, 36"),
        (10, 5, "10, 20, 30, 40, 50"),
        (11, 4, "11, 22, 33, 44"),
        (12, 4, "12, 24, 36, 48"),
    ]
    for k, n, ans in multiples_data:
        cs = ans.replace(", ", ",")
        qs.append(Q("fill", f"First {n} multiples of {k} (smallest first, comma-separated)",
                    answer=[cs, ans], explain=f"{ans}."))

    # Is X a multiple of Y? (MCQ Yes/No)
    multiple_yn = [
        (24, 6, True), (35, 4, False), (45, 9, True), (50, 7, False),
        (72, 8, True), (60, 11, False), (81, 9, True), (49, 6, False),
    ]
    for x, k, is_mult in multiple_yn:
        qs.append(Q("mcq", f"Is {x} a multiple of {k}?",
                    options=["Yes", "No"],
                    answer=0 if is_mult else 1,
                    explain=("Yes — " if is_mult else "No — ") + f"{k} × {x // k} = {k * (x // k)}."))

    # Factors
    factor_data = [
        (12, [1, 2, 3, 4, 6, 12]),
        (18, [1, 2, 3, 6, 9, 18]),
        (16, [1, 2, 4, 8, 16]),
        (24, [1, 2, 3, 4, 6, 8, 12, 24]),
        (20, [1, 2, 4, 5, 10, 20]),
        (15, [1, 3, 5, 15]),
        (28, [1, 2, 4, 7, 14, 28]),
        (36, [1, 2, 3, 4, 6, 9, 12, 18, 36]),
        (7, [1, 7]),
        (13, [1, 13]),
        (11, [1, 11]),
        (25, [1, 5, 25]),
    ]
    for n, fs in factor_data:
        cs = ",".join(str(x) for x in fs)
        sp = ", ".join(str(x) for x in fs)
        qs.append(Q("fill", f"List all factors of {n} (smallest first, comma-separated)",
                    answer=[cs, sp], explain=f"{sp}."))

    # Prime checks
    primes_data = [
        (11, True), (15, False), (13, True), (21, False),
        (17, True), (27, False), (19, True), (33, False),
        (23, True), (49, False), (29, True), (51, False),
        (31, True), (57, False), (37, True), (39, False),
    ]
    for n, is_prime in primes_data:
        if random.random() < 0.5:
            qs.append(Q("fill", f"Is {n} prime? (yes / no)",
                        answer=["yes" if is_prime else "no"],
                        explain=("Yes — only divisible by 1 and itself."
                                 if is_prime else f"No — has more than 2 factors.")))
        else:
            qs.append(Q("tf", f"{n} is a prime number.",
                        answer=0 if is_prime else 1,
                        explain=("True." if is_prime
                                 else "False — has divisors other than 1 and itself.")))

    # LCM
    lcm_data = [
        (4, 6, 12), (3, 5, 15), (4, 5, 20), (6, 8, 24),
        (3, 4, 12), (5, 6, 30), (8, 12, 24), (10, 15, 30),
        (2, 7, 14), (9, 12, 36), (6, 9, 18),
    ]
    for a, b, lcm in lcm_data:
        qs.append(Q("fill", f"LCM of {a} and {b} = ?",
                    answer=[str(lcm), fmt(lcm)],
                    explain=f"LCM({a}, {b}) = {lcm}."))

    # HCF
    hcf_data = [
        (12, 18, 6), (8, 12, 4), (10, 15, 5), (18, 27, 9),
        (16, 24, 8), (14, 21, 7), (20, 30, 10), (24, 36, 12),
        (15, 25, 5), (9, 12, 3), (18, 24, 6),
    ]
    for a, b, hcf in hcf_data:
        qs.append(Q("fill", f"HCF of {a} and {b} = ?",
                    answer=[str(hcf)],
                    explain=f"HCF({a}, {b}) = {hcf}."))

    # Divisibility rules
    div_qs = [
        ("A number ending in 0 is divisible by:",
         ["Only 5", "Only 10", "Both 2 and 5 (so by 10)", "Only 2"], 2,
         "Numbers ending in 0 are divisible by 2, 5, and 10."),
        ("A number ending in 5 is always divisible by:",
         ["2", "5", "10", "3"], 1,
         "Numbers ending in 5 are divisible by 5."),
        ("If the digit sum of a number is divisible by 3, the number is divisible by:",
         ["2", "3", "5", "7"], 1, "Yes — that's the divisibility rule for 3."),
        ("If the digit sum is divisible by 9, the number is divisible by:",
         ["3 only", "9 only", "Both 3 and 9", "Just 6"], 2,
         "Divisible by 9 means divisible by 3 too."),
        ("Sum of digits of 246 = 12 → is 246 divisible by 3?",
         ["Yes", "No"], 0, "12 is divisible by 3, so yes."),
        ("Sum of digits of 124 = 7 → is 124 divisible by 3?",
         ["Yes", "No"], 1, "7 is not divisible by 3, so no."),
    ]
    for q, opts, ans, ex in div_qs:
        qs.append(Q("mcq", q, options=opts, answer=ans, explain=ex))

    # Even/odd
    eo = [(34, "even"), (21, "odd"), (100, "even"), (87, "odd"),
          (1000, "even"), (53, "odd"), (456, "even"), (999, "odd")]
    for n, ans in eo:
        qs.append(Q("fill", f"Is {n} even or odd?",
                    answer=[ans], explain=f"{n} ends in {n % 10}, so {ans}."))

    # General
    qs += [
        Q("fill", "Smallest prime number = ?", answer=["2"],
          explain="2 — the only even prime."),
        Q("tf", "1 is a prime number.", answer=1,
          explain="False — 1 has only one factor (itself)."),
        Q("tf", "Every number is a multiple of 1.", answer=0,
          explain="True — N = N × 1."),
        Q("tf", "2 is the only even prime number.", answer=0,
          explain="True — every other even number is divisible by 2."),
        Q("fill", "Common factors of 8 and 12 (comma-separated, smallest first)",
          answer=["1,2,4", "1, 2, 4"], explain="1, 2, 4."),
        Q("fill", "Common factors of 9 and 15 (comma-separated, smallest first)",
          answer=["1,3", "1, 3"], explain="1, 3."),
        Q("fill", "Smallest multiple of 7 = ?", answer=["7"],
          explain="Every number's smallest multiple is itself."),
    ]
    return qs


# ============================================================
# Ch 4 — Geometry
# ============================================================
def gen_ch04():
    random.seed(404)
    qs = []

    # Polygon sides
    polygons = [
        ("triangle", 3), ("quadrilateral", 4), ("pentagon", 5),
        ("hexagon", 6), ("heptagon", 7), ("octagon", 8),
        ("nonagon", 9), ("decagon", 10),
    ]
    for name, sides in polygons:
        qs.append(Q("fill", f"How many sides does a {name} have?",
                    answer=[str(sides)], explain=f"A {name} has {sides} sides."))
        qs.append(Q("mcq", f"How many sides does a {name} have?",
                    options=[str(sides - 1), str(sides), str(sides + 1), str(sides + 2)],
                    answer=1, explain=f"{sides}."))

    # Angle types
    angles = [
        (90, "right"), (45, "acute"), (30, "acute"), (60, "acute"),
        (120, "obtuse"), (135, "obtuse"), (150, "obtuse"),
        (180, "straight"), (89, "acute"), (91, "obtuse"),
    ]
    for deg, kind in angles:
        qs.append(Q("fill", f"An angle of {deg}° is __ (acute/right/obtuse/straight)",
                    answer=[kind], explain=f"{deg}° is {kind}."))

    # 3D shape facts
    qs += [
        Q("fill", "A cube has __ faces.", answer=["6"], explain="6 faces."),
        Q("fill", "A cube has __ edges.", answer=["12"], explain="12 edges."),
        Q("fill", "A cube has __ vertices.", answer=["8"], explain="8 corners."),
        Q("fill", "A cuboid has __ faces.", answer=["6"], explain="6 rectangular faces."),
        Q("fill", "A cylinder has __ flat circular faces.", answer=["2"], explain="Top and bottom."),
        Q("fill", "A cone has __ flat face.", answer=["1"], explain="Just the circular base."),
        Q("fill", "A sphere has __ flat faces.", answer=["0"], explain="A sphere is round all over."),
        Q("fill", "A square pyramid has __ triangular faces.", answer=["4"],
          explain="4 triangles + 1 square base."),
        Q("mcq", "Which 3D shape has no flat faces?",
          options=["Cube", "Cylinder", "Cone", "Sphere"],
          answer=3, explain="A sphere is curved all over."),
        Q("mcq", "Which has exactly 1 vertex?",
          options=["Cube", "Cone", "Cylinder", "Cuboid"],
          answer=1, explain="A cone has 1 apex/vertex."),
    ]

    # Symmetry
    qs += [
        Q("fill", "A square has __ lines of symmetry.", answer=["4"], explain="4 — through middle vertically, horizontally, and 2 diagonals."),
        Q("fill", "A rectangle (not square) has __ lines of symmetry.", answer=["2"],
          explain="Vertical and horizontal middle lines only."),
        Q("fill", "An equilateral triangle has __ lines of symmetry.", answer=["3"],
          explain="One through each vertex."),
        Q("fill", "An isosceles triangle has __ lines of symmetry.", answer=["1"],
          explain="Through the apex."),
        Q("fill", "A scalene triangle has __ lines of symmetry.", answer=["0"],
          explain="No equal sides → no symmetry."),
        Q("fill", "A regular pentagon has __ lines of symmetry.", answer=["5"],
          explain="One through each vertex."),
        Q("fill", "A circle has __ lines of symmetry. (Hint: think 'unlimited')",
          answer=["infinite", "infinity", "unlimited", "many"],
          explain="Every line through the centre is a line of symmetry."),
        Q("fill", "The letter A has __ line(s) of symmetry.", answer=["1"],
          explain="Vertical line down the middle."),
        Q("fill", "The letter S has __ line(s) of symmetry.", answer=["0"],
          explain="None — S is not symmetric."),
    ]

    # Lines
    qs += [
        Q("fill", "Lines that never meet are called __ lines.", answer=["parallel"],
          explain="Parallel lines stay the same distance apart."),
        Q("fill", "Lines that meet at 90° are called __ lines.", answer=["perpendicular"],
          explain="Perpendicular = right-angle meeting."),
        Q("fill", "Lines that cross are called __ lines.", answer=["intersecting"],
          explain="They share a point."),
        Q("mcq", "Railway tracks are an example of:",
          options=["Parallel lines", "Perpendicular lines", "Curved lines"],
          answer=0, explain="Tracks stay the same distance apart."),
        Q("mcq", "The corners of a square are:",
          options=["Acute angles", "Right angles", "Obtuse angles", "Straight angles"],
          answer=1, explain="All 4 corners of a square are right angles (90°)."),
    ]

    # Circle
    qs += [
        Q("fill", "The distance from the centre of a circle to its edge is the __",
          answer=["radius"], explain="Radius = centre to edge."),
        Q("fill", "The distance straight across a circle through the centre is the __",
          answer=["diameter"], explain="Diameter = 2 × radius."),
        Q("fill", "If radius = 5 cm, diameter = ? cm", answer=["10"], explain="2 × 5 = 10."),
        Q("fill", "If radius = 8 cm, diameter = ? cm", answer=["16"], explain="2 × 8 = 16."),
        Q("fill", "If diameter = 14 cm, radius = ? cm", answer=["7"], explain="14 ÷ 2 = 7."),
        Q("fill", "If diameter = 24 cm, radius = ? cm", answer=["12"], explain="24 ÷ 2 = 12."),
        Q("fill", "The line that touches a circle at exactly one point is called a __",
          answer=["tangent"], explain="A tangent touches at one point."),
    ]

    # Angle sums
    qs += [
        Q("fill", "Sum of all angles in a triangle = ? degrees", answer=["180"],
          explain="Always 180°."),
        Q("fill", "Sum of all angles in a square = ? degrees", answer=["360"],
          explain="4 × 90 = 360."),
        Q("fill", "Sum of all angles in a rectangle = ? degrees", answer=["360"],
          explain="4 right angles."),
        Q("fill", "Sum of all angles in a quadrilateral = ? degrees", answer=["360"],
          explain="Always 360° in any quadrilateral."),
        Q("fill", "Each angle in an equilateral triangle = ? degrees", answer=["60"],
          explain="180 ÷ 3 = 60."),
        Q("fill", "Each angle in a square = ? degrees", answer=["90"],
          explain="All angles are right."),
    ]

    # T/F
    qs += [
        Q("tf", "A square is also a rectangle.", answer=0,
          explain="True — special rectangle with all sides equal."),
        Q("tf", "All squares are rhombuses.", answer=0,
          explain="True — squares have 4 equal sides like rhombuses."),
        Q("tf", "A triangle can have two right angles.", answer=1,
          explain="False — angles would already sum to 180° before the third angle."),
        Q("tf", "A circle has 4 sides.", answer=1,
          explain="False — a circle has no straight sides."),
    ]
    return qs


# ============================================================
# Ch 5 — Decimals
# ============================================================
def gen_ch05():
    random.seed(505)
    qs = []

    # Place value identification (mcq)
    pv_data = [
        (4.27, "2", 0.2, "tenths"),
        (3.07, "7", 0.07, "hundredths"),
        (7.085, "8", 0.08, "hundredths"),
        (6.21, "1", 0.01, "hundredths"),
        (5.43, "3", 0.03, "hundredths"),
        (9.6, "6", 0.6, "tenths"),
        (2.137, "7", 0.007, "thousandths"),
        (1.4, "4", 0.4, "tenths"),
    ]
    for num, digit, val, place in pv_data:
        # Build distractors
        opts = sorted({val, val * 10, val / 10, float(digit), float(digit) * 10}, key=str)
        if len(opts) < 4:
            opts.append(0)
        opts = list(opts)[:4]
        if val not in opts: opts[0] = val
        random.shuffle(opts)
        idx = opts.index(val)
        # Format options
        opts_s = [str(o) if o == int(o) else str(o) for o in opts]
        qs.append(Q("mcq", f"In {num}, what is the value of {digit}?",
                    options=opts_s, answer=idx,
                    explain=f"{digit} is in the {place} place → {val}."))

    # Place value (fill — bidirectional, accept place name OR value)
    pv_fill = [
        (4.27, "2", "0.2", "tenths"),
        (3.07, "7", "0.07", "hundredths"),
        (7.085, "8", "0.08", "hundredths"),
        (6.21, "1", "0.01", "hundredths"),
        (9.6, "6", "0.6", "tenths"),
        (8.142, "4", "0.04", "hundredths"),
    ]
    for num, digit, val, place in pv_fill:
        qs.append(Q("fill", f"In {num}, what is the place value of {digit}?",
                    answer=[val, val.lstrip("0"),
                            f"{digit} {place}", place, f"{place} place"],
                    explain=f"{digit} sits in the {place} place. Place value = {val}. Either '{place}' or '{val}' is fine."))

    # Fraction → decimal
    fd_data = [
        ("1/2", "0.5"), ("1/4", "0.25"), ("3/4", "0.75"),
        ("1/5", "0.2"), ("2/5", "0.4"), ("3/5", "0.6"), ("4/5", "0.8"),
        ("1/10", "0.1"), ("3/10", "0.3"), ("7/10", "0.7"), ("9/10", "0.9"),
        ("1/8", "0.125"), ("1/100", "0.01"),
    ]
    for frac, dec in fd_data:
        bare = dec.lstrip("0")
        qs.append(Q("fill", f"{frac} as a decimal = ?",
                    answer=[dec, bare], explain=f"{frac} = {dec}."))

    # Decimal → fraction (MCQ to keep simple)
    df = [
        ("0.5", "1/2"), ("0.25", "1/4"), ("0.75", "3/4"),
        ("0.1", "1/10"), ("0.2", "1/5"), ("0.4", "2/5"),
    ]
    for dec, frac in df:
        opts = ["1/2", "1/4", "3/4", "1/10", "1/5", "2/5"]
        random.shuffle(opts)
        if frac not in opts: opts[0] = frac
        opts = opts[:4]
        if frac not in opts: opts[0] = frac
        random.shuffle(opts)
        qs.append(Q("mcq", f"{dec} = which fraction?",
                    options=opts, answer=opts.index(frac),
                    explain=f"{dec} = {frac}."))

    # Addition
    for _ in range(8):
        a = round(random.uniform(0.1, 9.9), 1)
        b = round(random.uniform(0.1, 9.9), 1)
        s = round(a + b, 2)
        qs.append(Q("fill", f"{a} + {b} = ?",
                    answer=[str(s), str(s).lstrip("0")],
                    explain=f"{a} + {b} = {s}."))

    # Subtraction
    for _ in range(8):
        a = round(random.uniform(2, 10), 1)
        b = round(random.uniform(0.1, a - 0.1), 1)
        d = round(a - b, 2)
        qs.append(Q("fill", f"{a} − {b} = ?",
                    answer=[str(d), str(d).lstrip("0")],
                    explain=f"{a} − {b} = {d}."))

    # Rounding
    rounds = [
        ("Round 4.67 to whole = ?", "5", "0.67 ≥ 0.5 → up."),
        ("Round 8.42 to whole = ?", "8", "0.42 < 0.5 → down."),
        ("Round 3.456 to nearest tenth = ?", "3.5", "Hundredths digit 5 → up."),
        ("Round 2.68 to nearest tenth = ?", "2.7", "Hundredths digit 8 → up."),
        ("Round 9.51 to whole = ?", "10", "0.51 ≥ 0.5 → up."),
        ("Round 0.83 to nearest tenth = ?", "0.8", "Hundredths 3 < 5 → down."),
        ("Round 1.99 to nearest tenth = ?", "2", "Hundredths 9 → up. Carry over to whole 2."),
    ]
    for q, ans, ex in rounds:
        qs.append(Q("fill", q, answer=[ans, ans.lstrip("0")], explain=ex))

    # Compare
    pairs = [
        ("0.5", "0.45", "0.5"), ("0.7", "0.07", "0.7"),
        ("3.05", "3.005", "3.05"), ("0.9", "0.099", "0.9"),
        ("1.5", "1.50", "equal"), ("2.3", "2.30", "equal"),
    ]
    for a, b, larger in pairs:
        if larger == "equal":
            qs.append(Q("compare", f"Compare: {a} ___ {b}",
                        options=["<", ">", "="], answer=2,
                        explain=f"{a} = {b} (trailing zeros don't change value)."))
        else:
            sign = 0 if larger == b else 1
            qs.append(Q("compare", f"Compare: {a} ___ {b}",
                        options=["<", ">", "="], answer=sign,
                        explain=f"{larger} is larger."))

    # ×/÷ by powers of 10
    qs += [
        Q("fill", "0.5 × 10 = ?", answer=["5"], explain="Move decimal 1 right."),
        Q("fill", "0.5 × 100 = ?", answer=["50"], explain="Move decimal 2 right."),
        Q("fill", "3 ÷ 10 = ?", answer=["0.3", ".3"], explain="Move decimal 1 left."),
        Q("fill", "12 ÷ 100 = ?", answer=["0.12", ".12"], explain="Move decimal 2 left."),
        Q("fill", "2.5 × 10 = ?", answer=["25"], explain="Move decimal 1 right."),
    ]

    # T/F & word
    qs += [
        Q("tf", "0.30 and 0.3 are equal.", answer=0,
          explain="True — trailing zeros after the decimal don't change value."),
        Q("tf", "0.5 < 0.50.", answer=1, explain="False — equal."),
        Q("tf", "0.9 is bigger than 0.91.", answer=1,
          explain="False — 0.91 has more in the hundredths."),
        Q("fill", "How many tenths in 1?", answer=["10"], explain="1 = 10/10."),
        Q("fill", "How many hundredths in 0.1?", answer=["10"], explain="0.1 = 10/100."),
        Q("fill", 'Write "two and three tenths" as a decimal.', answer=["2.3"], explain="2 + 3/10."),
        Q("fill", 'Write "0.07" in words.',
          answer=["seven hundredths", "zero point zero seven", "point zero seven"],
          explain="7 in the hundredths place."),
    ]
    return qs


# ============================================================
# Ch 6 — Perimeter, Area, Volume
# ============================================================
def gen_ch06():
    random.seed(606)
    qs = []

    # Square perimeter
    for s in [3, 4, 5, 6, 7, 8, 9, 10, 12, 15, 20]:
        qs.append(Q("fill", f"Perimeter of a square with side {s} cm?",
                    answer=[str(4 * s), f"{4*s} cm", f"{4*s}cm"],
                    explain=f"P = 4 × {s} = {4*s} cm."))

    # Rectangle perimeter
    for L, W in [(6, 4), (8, 3), (10, 5), (12, 7), (15, 8), (9, 6), (20, 10), (7, 4)]:
        p = 2 * (L + W)
        qs.append(Q("fill", f"Perimeter of a rectangle {L} × {W} cm?",
                    answer=[str(p), f"{p} cm", f"{p}cm"],
                    explain=f"P = 2(L+W) = 2({L}+{W}) = {p} cm."))

    # Square area
    for s in [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 15]:
        qs.append(Q("fill", f"Area of a square with side {s} cm?",
                    answer=[str(s * s), f"{s*s} sq cm", f"{s*s} cm²"],
                    explain=f"A = s² = {s*s} sq cm."))

    # Rectangle area
    for L, W in [(8, 3), (12, 5), (10, 4), (15, 6), (9, 7), (20, 8), (11, 5), (14, 9)]:
        a = L * W
        qs.append(Q("fill", f"Area of a rectangle {L} × {W} cm?",
                    answer=[str(a), f"{a} sq cm", f"{a} cm²"],
                    explain=f"A = L×W = {a} sq cm."))

    # Cube volume
    for s in [2, 3, 4, 5, 6, 7, 8, 10]:
        v = s ** 3
        qs.append(Q("fill", f"Volume of a cube with side {s} cm?",
                    answer=[str(v), f"{v} cu cm", f"{v} cm³"],
                    explain=f"V = s³ = {v} cu cm."))

    # Cuboid volume
    for L, W, H in [(4, 3, 2), (5, 4, 3), (6, 4, 2), (7, 5, 3), (8, 6, 4), (10, 5, 2), (3, 3, 5)]:
        v = L * W * H
        qs.append(Q("fill", f"Volume of a cuboid {L}×{W}×{H} cm?",
                    answer=[str(v), f"{v} cu cm", f"{v} cm³"],
                    explain=f"V = {L}×{W}×{H} = {v} cu cm."))

    # Find side from area
    for a in [9, 16, 25, 36, 49, 64, 81, 100, 144]:
        s = int(a ** 0.5)
        qs.append(Q("fill", f"Square area = {a} sq cm. Side = ?",
                    answer=[str(s), f"{s} cm", f"{s}cm"],
                    explain=f"√{a} = {s} cm."))

    # Find side from cube volume
    for s in [2, 3, 4, 5, 6, 7]:
        v = s ** 3
        qs.append(Q("fill", f"Cube volume = {v} cu cm. Side = ?",
                    answer=[str(s), f"{s} cm"], explain=f"∛{v} = {s} cm."))

    # Triangle/polygon perimeters
    qs += [
        Q("fill", "Perimeter of a triangle with sides 3, 4, 5 cm?", answer=["12", "12 cm"], explain="3+4+5=12."),
        Q("fill", "Perimeter of a triangle with sides 6, 8, 10 cm?", answer=["24", "24 cm"], explain="6+8+10=24."),
        Q("fill", "Perimeter of a regular pentagon with side 6 cm?",
          answer=["30", "30 cm"], explain="5 × 6 = 30."),
        Q("fill", "Perimeter of a regular hexagon with side 4 cm?",
          answer=["24", "24 cm"], explain="6 × 4 = 24."),
        Q("fill", "Perimeter of a regular octagon with side 3 cm?",
          answer=["24", "24 cm"], explain="8 × 3 = 24."),
    ]

    # Units MCQ
    qs += [
        Q("mcq", "Perimeter is measured in:",
          options=["cm", "cm²", "cm³", "kg"], answer=0, explain="Length unit."),
        Q("mcq", "Area is measured in:",
          options=["cm", "cm²", "cm³", "L"], answer=1, explain="Square units."),
        Q("mcq", "Volume is measured in:",
          options=["cm", "cm²", "cm³", "g"], answer=2, explain="Cubic units."),
    ]

    # Conversions
    qs += [
        Q("fill", "1 m = ? cm", answer=["100"], explain="1 m = 100 cm."),
        Q("fill", "1 sq m = ? sq cm", answer=["10000", "10,000"], explain="100 × 100."),
        Q("fill", "1 cu m = ? cu cm",
          answer=["1000000", "1,000,000"], explain="100 × 100 × 100."),
    ]

    # T/F
    qs += [
        Q("tf", "A bigger perimeter always means a bigger area.", answer=1,
          explain="False — long thin rectangle vs square."),
        Q("tf", "Volume measures the surface of a 3D shape.", answer=1,
          explain="False — that's surface area. Volume is the SPACE inside."),
        Q("tf", "All squares are rectangles.", answer=0,
          explain="True — square = special rectangle with equal sides."),
    ]
    return qs


# ============================================================
# Ch 7 — Speed & Temperature
# ============================================================
def gen_ch07():
    random.seed(707)
    qs = []

    # S = D/T
    for d, t in [(120, 2), (90, 3), (200, 5), (240, 3), (150, 5), (180, 6),
                 (100, 4), (60, 2), (300, 5), (240, 4), (320, 8), (175, 5)]:
        s = d // t
        qs.append(Q("fill", f"{d} km in {t} h. Speed (km/h) = ?",
                    answer=[str(s), f"{s} km/h"],
                    explain=f"S = D/T = {d}/{t} = {s} km/h."))

    # D = S × T
    for s, t in [(15, 4), (50, 6), (80, 2), (60, 3), (40, 5), (25, 4),
                 (90, 2), (35, 3), (45, 4), (100, 2), (70, 3), (55, 6)]:
        d = s * t
        qs.append(Q("fill", f"{s} km/h × {t} h = ? km",
                    answer=[str(d), f"{d} km"],
                    explain=f"D = S×T = {s}×{t} = {d} km."))

    # T = D/S
    for d, s in [(100, 25), (60, 20), (200, 40), (100, 50), (180, 60),
                 (90, 30), (120, 40), (240, 60), (150, 50), (300, 50)]:
        t = d // s
        qs.append(Q("fill", f"{d} km at {s} km/h = ? hours",
                    answer=[str(t), f"{t} hours", f"{t}h"],
                    explain=f"T = D/S = {d}/{s} = {t} hours."))

    # Temperature basics
    qs += [
        Q("fill", "Water freezes at __ °C", answer=["0"], explain="Freezing point of water."),
        Q("fill", "Water boils at __ °C", answer=["100"], explain="Boiling point of water."),
        Q("fill", "Normal body temperature ≈ __ °C", answer=["37"],
          explain="About 37°C (98.6°F)."),
        Q("mcq", "Bahrain summer noon ≈ how many °C?",
          options=["10°C", "25°C", "45°C", "70°C"], answer=2,
          explain="Around 40-45°C in peak summer."),
        Q("mcq", "Which is colder?",
          options=["10°C", "0°C", "-5°C"], answer=2,
          explain="-5°C is below freezing → coldest."),
        Q("mcq", "Which is hotter?",
          options=["20°C", "35°C", "5°C"], answer=1, explain="35°C is the warmest."),
    ]

    # Temperature differences
    for a, b in [(35, 18), (40, 22), (28, 15), (50, 25), (38, 20),
                 (30, 10), (45, 30), (25, 5), (37, 22), (55, 38)]:
        d = a - b
        qs.append(Q("fill", f"{a}°C − {b}°C = ?", answer=[str(d), f"{d}°C"],
                    explain=f"Difference = {d}°C."))

    # T/F & word
    qs += [
        Q("tf", "Negative temperatures (like -3°C) mean below freezing.", answer=0,
          explain="True — below 0°C is freezing cold."),
        Q("tf", "1 hour and 60 minutes are the same.", answer=0, explain="True."),
        Q("fill", "If a car travels 80 km/h for 30 min, it covers __ km.",
          answer=["40", "40 km"], explain="Half hour at 80 = 40 km."),
        Q("fill", "Light's speed is about __ km/sec (hint: 3 lakh).",
          answer=["300000", "3,00,000", "300,000"],
          explain="≈ 300,000 km/sec."),
        Q("fill", "If the temperature rose from 22°C to 30°C, the rise is __ °C.",
          answer=["8"], explain="30 − 22 = 8."),
    ]
    return qs


# ============================================================
# Ch 8 — Data Handling
# ============================================================
def gen_ch08():
    random.seed(808)
    qs = []

    # Mean — generate diverse sets
    def mean_q():
        n = random.choice([3, 4, 5, 6])
        nums = [random.randint(2, 25) for _ in range(n)]
        # Force integer mean by adjusting
        s = sum(nums)
        if s % n != 0:
            nums[-1] += (n - (s % n))
            s = sum(nums)
        m = s // n
        nums_s = ", ".join(str(x) for x in nums)
        qs.append(Q("fill", f"Mean of {nums_s} = ?",
                    answer=[str(m)], explain=f"Sum = {s}, divide by {n} = {m}."))
    for _ in range(15):
        mean_q()

    # Mode
    def mode_q():
        common = random.randint(2, 9)
        others = random.sample([x for x in range(2, 15) if x != common], 3)
        nums = [common] * random.randint(2, 3) + others
        random.shuffle(nums)
        nums_s = ", ".join(str(x) for x in nums)
        qs.append(Q("fill", f"Mode of {nums_s} = ?",
                    answer=[str(common)], explain=f"{common} appears most often."))
    for _ in range(12):
        mode_q()

    # Range
    def range_q():
        nums = [random.randint(1, 30) for _ in range(random.randint(4, 6))]
        r = max(nums) - min(nums)
        nums_s = ", ".join(str(x) for x in nums)
        qs.append(Q("fill", f"Range of {nums_s} = ?",
                    answer=[str(r)], explain=f"Max {max(nums)} − min {min(nums)} = {r}."))
    for _ in range(12):
        range_q()

    # Pictograph (1 ⚽ = 5 goals)
    for n in [2, 3, 4, 5, 6, 7, 8, 10]:
        symbols = "⚽" * n
        qs.append(Q("fill", f"If 1 ⚽ = 5 goals, {symbols} = __ goals",
                    answer=[str(n * 5)], explain=f"{n} × 5 = {n*5}."))

    # Pictograph (1 ⭐ = 10 books)
    for n in [2, 3, 4, 5, 6]:
        symbols = "⭐" * n
        qs.append(Q("fill", f"If 1 ⭐ = 10 books, {symbols} = __ books",
                    answer=[str(n * 10)], explain=f"{n} × 10 = {n*10}."))

    # Tally
    qs += [
        Q("mcq", "A tally mark of |||| crossed by another | shows the number:",
          options=["4", "5", "6", "10"], answer=1,
          explain="A bundle of 5."),
        Q("fill", "How many marks: ||||  |||  ?",
          answer=["8"], explain="4 + 3 = 8."),
        Q("fill", "If one bundle = 5, two bundles + 3 = __",
          answer=["13"], explain="5+5+3=13."),
    ]

    # Concept MCQs
    qs += [
        Q("mcq", '"Mean" is also called:',
          options=["Average", "Most common", "Middle", "Total"],
          answer=0, explain="Mean = average."),
        Q("mcq", '"Mode" is:',
          options=["The biggest", "The most common (repeated) value",
                   "The average", "The smallest"],
          answer=1, explain="Mode = most common value."),
        Q("mcq", '"Range" is:',
          options=["Total", "Difference between highest and lowest",
                   "Middle value", "Average"],
          answer=1, explain="Range = max − min."),
        Q("mcq", "A bar graph uses:",
          options=["Lines", "Bars (rectangles)", "Slices", "Dots"],
          answer=1, explain="Bars."),
        Q("mcq", "A pie chart uses:",
          options=["Bars", "Slices of a circle", "Lines", "Squares"],
          answer=1, explain="Circular slices."),
        Q("mcq", "A pictograph uses:",
          options=["Numbers", "Pictures or symbols", "Lines", "Bars"],
          answer=1, explain="Pictures/symbols."),
        Q("mcq", "A line graph is best for showing:",
          options=["Static counts", "Changes over time", "Categories", "Slices"],
          answer=1, explain="Trends over time."),
    ]

    # T/F
    qs += [
        Q("tf", "Mean and average are the same thing.", answer=0, explain="True."),
        Q("tf", "A data set can have more than one mode.", answer=0,
          explain="True — bimodal sets exist."),
        Q("tf", "Mean is always one of the values in the data set.", answer=1,
          explain="False — can be a non-listed value (even a decimal)."),
    ]
    return qs


# ============================================================
# Ch 9 — Measurement
# ============================================================
def gen_ch09():
    random.seed(909)
    qs = []

    # Length: m → cm
    for m in [1, 2, 3, 4, 5, 6, 7, 8, 10, 12, 15, 20, 25]:
        qs.append(Q("fill", f"{m} m = ? cm",
                    answer=[str(m * 100), fmt(m * 100)],
                    explain=f"× 100: {m * 100} cm."))

    # cm → m
    for cm in [100, 200, 300, 500, 750, 1500, 250, 1000, 2000]:
        m = cm / 100
        m_str = str(int(m)) if m == int(m) else str(m)
        qs.append(Q("fill", f"{cm} cm = ? m",
                    answer=[m_str, m_str.lstrip("0")],
                    explain=f"÷ 100: {m_str} m."))

    # km → m
    for km in [1, 2, 3, 4, 5, 6, 8, 10]:
        qs.append(Q("fill", f"{km} km = ? m",
                    answer=[str(km * 1000), fmt(km * 1000)],
                    explain=f"× 1000: {fmt(km * 1000)} m."))

    # m → km
    for m in [1000, 2000, 3500, 4500, 5000, 7500, 10000]:
        km = m / 1000
        km_s = str(int(km)) if km == int(km) else str(km)
        qs.append(Q("fill", f"{m} m = ? km",
                    answer=[km_s, km_s.lstrip("0")],
                    explain=f"÷ 1000: {km_s} km."))

    # kg → g
    for kg in [1, 2, 3, 5, 7, 10, 15]:
        qs.append(Q("fill", f"{kg} kg = ? g",
                    answer=[str(kg * 1000), fmt(kg * 1000)],
                    explain=f"× 1000: {fmt(kg * 1000)} g."))

    # g → kg
    for g in [500, 750, 1000, 1500, 2500, 3000, 4500, 6000]:
        kg = g / 1000
        kg_s = str(int(kg)) if kg == int(kg) else str(kg)
        qs.append(Q("fill", f"{g} g = ? kg",
                    answer=[kg_s, kg_s.lstrip("0")],
                    explain=f"÷ 1000: {kg_s} kg."))

    # L → mL
    for L in [1, 2, 3, 4, 5, 7, 10]:
        qs.append(Q("fill", f"{L} L = ? mL",
                    answer=[str(L * 1000), fmt(L * 1000)],
                    explain=f"× 1000: {fmt(L * 1000)} mL."))

    # mL → L
    for ml in [500, 750, 1000, 1500, 2000, 2500, 3500, 4000]:
        L = ml / 1000
        L_s = str(int(L)) if L == int(L) else str(L)
        qs.append(Q("fill", f"{ml} mL = ? L",
                    answer=[L_s, L_s.lstrip("0")],
                    explain=f"÷ 1000: {L_s} L."))

    # Mixed units
    mixed = [
        ("1 m 45 cm in cm", "145"),
        ("2 m 30 cm in cm", "230"),
        ("1 m 75 cm in cm", "175"),
        ("3 m 8 cm in cm", "308"),
        ("1 kg 250 g in g", "1250"),
        ("2 kg 500 g in g", "2500"),
        ("3 kg 100 g in g", "3100"),
        ("2 L 500 mL in mL", "2500"),
        ("1 L 750 mL in mL", "1750"),
        ("3 L 250 mL in mL", "3250"),
    ]
    for q, ans in mixed:
        qs.append(Q("fill", q, answer=[ans, fmt(int(ans))], explain=f"= {fmt(int(ans))}."))

    # Comparisons
    cmp = [
        ("1 km", "500 m", "1 km"), ("2 kg", "1500 g", "2 kg"),
        ("1 L", "750 mL", "1 L"), ("1 m", "90 cm", "1 m"),
        ("3 km", "2900 m", "3 km"), ("500 g", "0.6 kg", "0.6 kg"),
    ]
    for a, b, larger in cmp:
        qs.append(Q("fill", f"Larger of {a} and {b}? Type the larger one.",
                    answer=[larger, larger.lower(), larger.replace(" ", "")],
                    explain=f"{larger} is larger."))

    # MCQs
    qs += [
        Q("mcq", "Which is the largest?",
          options=["1 km", "500 m", "2000 cm", "5 m"], answer=0, explain="1 km = 1000 m."),
        Q("mcq", "Which weighs the most?",
          options=["500 g", "2 kg", "1500 g", "0.5 kg"], answer=1, explain="2 kg = 2000 g."),
        Q("mcq", "Which holds the most water?",
          options=["250 mL", "1 L", "750 mL", "500 mL"], answer=1, explain="1 L = 1000 mL."),
    ]

    # T/F
    qs += [
        Q("tf", "1.5 kg = 1500 g.", answer=0, explain="True — × 1000."),
        Q("tf", "1 m is shorter than 90 cm.", answer=1, explain="False — 1 m = 100 cm > 90 cm."),
        Q("tf", "1 L = 1000 mL.", answer=0, explain="True."),
    ]
    return qs


# ============================================================
# Ch 10 — Time & Money
# ============================================================
def gen_ch10():
    random.seed(1010)
    qs = []

    # Time conversion basics
    qs += [
        Q("fill", "1 hour = ? minutes", answer=["60"], explain="60."),
        Q("fill", "1 minute = ? seconds", answer=["60"], explain="60."),
        Q("fill", "1 day = ? hours", answer=["24"], explain="24."),
        Q("fill", "1 week = ? days", answer=["7"], explain="7."),
        Q("fill", "1 year = ? months", answer=["12"], explain="12."),
        Q("fill", "1 hour = ? seconds", answer=["3600", "3,600"], explain="60×60=3600."),
        Q("fill", "Half an hour = ? minutes", answer=["30"], explain="60/2=30."),
        Q("fill", "2 hours = ? minutes", answer=["120"], explain="60×2=120."),
        Q("fill", "3 hours = ? minutes", answer=["180"], explain="60×3=180."),
        Q("fill", "90 seconds = ? minutes and seconds (e.g. 1 min 30 sec)",
          answer=["1 min 30 sec", "1 minute 30 seconds", "1m 30s", "1:30"],
          explain="60 + 30 = 90."),
        Q("fill", "150 minutes = ? hours and minutes",
          answer=["2 h 30 min", "2 hours 30 minutes", "2:30", "2h 30min"],
          explain="60+60+30=150."),
    ]

    # 24-hour to 12-hour and vice-versa
    times = [
        ("15:00", "3 pm"), ("18:30", "6:30 pm"), ("20:00", "8 pm"),
        ("21:30", "9:30 pm"), ("13:15", "1:15 pm"), ("17:45", "5:45 pm"),
        ("22:10", "10:10 pm"), ("19:00", "7 pm"), ("14:00", "2 pm"),
        ("23:30", "11:30 pm"),
    ]
    for t24, t12 in times:
        qs.append(Q("fill", f"{t24} in 12-hour format = ?",
                    answer=[t12, t12.replace(" ", ""), t12 + ".", t12 + " p.m."],
                    explain=f"{t24} − 12:00 → {t12}."))
        # Reverse
        qs.append(Q("fill", f"{t12.upper()} in 24-hour format = ?",
                    answer=[t24, t24.replace(":", "")],
                    explain=f"{t12} → {t24}."))

    # Elapsed time
    elapsed = [
        ("9 AM to 5 PM", 8, "5pm = 17:00; 17 − 9 = 8 hours."),
        ("8 AM to 12 noon", 4, "12 − 8 = 4 hours."),
        ("10 AM to 4 PM", 6, "16 − 10 = 6 hours."),
        ("7 AM to 7 PM", 12, "19 − 7 = 12 hours."),
        ("1 PM to 5 PM", 4, "17 − 13 = 4 hours."),
    ]
    for q, ans, ex in elapsed:
        qs.append(Q("fill", f"From {q} = __ hours",
                    answer=[str(ans)], explain=ex))

    # Movie end time
    movies = [
        ("4:30 PM", "2 h", "6:30 pm"),
        ("3:00 PM", "1 h 30 min", "4:30 pm"),
        ("7:00 PM", "2 h 15 min", "9:15 pm"),
        ("10:00 AM", "3 h", "1 pm"),
        ("11:00 AM", "1 h 30 min", "12:30 pm"),
    ]
    for start, dur, end in movies:
        qs.append(Q("fill", f"Movie starts {start}, runs {dur}. Ends at?",
                    answer=[end, end.replace(" ", ""), end.replace("pm", "PM"),
                            end + ".", end.replace("pm", "p.m.")],
                    explain=f"{start} + {dur} = {end}."))

    # Calendar
    qs += [
        Q("mcq", "How many days in February (non-leap year)?",
          options=["28", "29", "30", "31"], answer=0,
          explain="28 normally, 29 in a leap year."),
        Q("mcq", "How many months have 31 days?",
          options=["5", "6", "7", "12"], answer=2,
          explain="Jan, Mar, May, Jul, Aug, Oct, Dec = 7."),
        Q("mcq", "Which month has 30 days?",
          options=["February", "March", "September", "May"], answer=2,
          explain="Sep, Apr, Jun, Nov = 30 days."),
        Q("mcq", "How many days in a leap year?",
          options=["365", "366", "364", "367"], answer=1, explain="366."),
        Q("mcq", "1 century = ? years",
          options=["10", "50", "100", "1000"], answer=2, explain="100."),
        Q("mcq", "1 decade = ? years",
          options=["10", "100", "1000", "5"], answer=0, explain="10."),
    ]

    # Money — BHD/fils
    qs += [
        Q("fill", "1 BHD = ? fils", answer=["1000", "1,000"], explain="1000."),
        Q("fill", "1 rupee (₹) = ? paise", answer=["100"], explain="100."),
    ]
    for fils, bhd in [(500, "0.5"), (250, "0.25"), (750, "0.75"), (2500, "2.5"),
                     (1500, "1.5"), (5000, "5"), (3750, "3.75"), (100, "0.1")]:
        qs.append(Q("fill", f"{fils} fils = ? BHD",
                    answer=[bhd, bhd.lstrip("0")],
                    explain=f"÷ 1000: {bhd} BHD."))

    # Money math (BHD)
    money_math = [
        ("2.500 + 1.250", "3.75", "3.750"),
        ("3.000 + 4.500", "7.5", "7.500"),
        ("5.250 + 2.750", "8", "8.000"),
        ("10 − 5.250", "4.75", "4.750"),
        ("3.000 − 2.250", "0.75", "0.750"),
        ("7.500 − 2.500", "5", "5.000"),
        ("3 × 2.000", "6", "6.000"),
        ("4 × 1.250", "5", "5.000"),
        ("8.000 ÷ 4", "2", "2.000"),
    ]
    for q, a1, a2 in money_math:
        qs.append(Q("fill", f"{q} BHD = ?",
                    answer=[a1, a2, a1 + " BHD"],
                    explain=f"{q} = {a2} BHD."))

    # Money word problems (₹)
    money_words = [
        ("Juice ₹15 each. 4 juices = ₹?", 60),
        ("Pen ₹8 + book ₹25. Total ₹?", 33),
        ("Crispin has ₹500. Spends ₹275. Left ₹?", 225),
        ("3 toys cost ₹240. One toy ₹?", 80),
        ("A pencil case ₹120. Pay with ₹500. Change ₹?", 380),
        ("8 chocolates × ₹12 = ₹?", 96),
        ("₹100 split among 5 friends. Each gets ₹?", 20),
    ]
    for q, ans in money_words:
        qs.append(Q("fill", q, answer=[str(ans)], explain=f"= ₹{ans}."))

    # T/F
    qs += [
        Q("tf", "13:00 is the same as 3:00 PM.", answer=1, explain="False — 13:00 = 1 PM."),
        Q("tf", "1 hour and 60 minutes are the same.", answer=0, explain="True."),
    ]
    return qs


# ============================================================
# Run
# ============================================================
if __name__ == "__main__":
    print("Generating expanded exam banks...")
    write_bank("ch02-four-operations.js", "CH02_BANK", gen_ch02())
    write_bank("ch03-multiples-factors.js", "CH03_BANK", gen_ch03())
    write_bank("ch04-geometry.js", "CH04_BANK", gen_ch04())
    write_bank("ch05-decimals.js", "CH05_BANK", gen_ch05())
    write_bank("ch06-perimeter-area-volume.js", "CH06_BANK", gen_ch06())
    write_bank("ch07-speed-temperature.js", "CH07_BANK", gen_ch07())
    write_bank("ch08-data-handling.js", "CH08_BANK", gen_ch08())
    write_bank("ch09-measurement.js", "CH09_BANK", gen_ch09())
    write_bank("ch10-time-money.js", "CH10_BANK", gen_ch10())
    print("Done.")
